export const EN_LABELS = {
  personalInfo: 'Personal Information',
  physicalAttributes: 'Physical Attributes',
  religiousInfo: 'Religious Information',
  education: 'Educational Background',
  professional: 'Professional Information',
  familyInfo: 'Family Information',
  siblingDetails: 'Sibling Details',
  contactInfo: 'Contact Information',
  partnerPreferences: 'Partner Preferences',
  fullName: 'Full Name',
  dateOfBirth: 'Date of Birth',
  placeOfBirth: 'Place of Birth',
  nationality: 'Nationality',
  religion: 'Religion',
  maritalStatus: 'Marital Status',
  height: 'Height',
  complexion: 'Complexion',
  bloodGroup: 'Blood Group',
  weight: 'Weight',
  sect: 'Sect',
  prayerHabit: 'Prayer Habit',
  degree: 'Degree',
  institution: 'Institution',
  passingYear: 'Year',
  result: 'Result',
  jobTitle: 'Job Title',
  organization: 'Organization',
  duration: 'Duration',
  income: 'Monthly Income',
  fatherName: "Father's Name",
  fatherOccupation: "Father's Occupation",
  motherName: "Mother's Name",
  motherOccupation: "Mother's Occupation",
  brothers: 'Brothers',
  sisters: 'Sisters',
  familyType: 'Family Type',
  familyStatus: 'Family Status',
  nativeDistrict: 'Native District',
  name: 'Name',
  gender: 'Gender',
  phone: 'Phone',
  email: 'Email',
  presentAddress: 'Present Address',
  permanentAddress: 'Permanent Address',
  ageRange: 'Age Range',
  educationPref: 'Education',
  profession: 'Profession',
  district: 'District',
  otherRequirements: 'Other Requirements',
  male: 'Male',
  female: 'Female',
  neverMarried: 'Never Married',
  divorced: 'Divorced',
  widowed: 'Widowed',
  nuclear: 'Nuclear',
  joint: 'Joint',
};

export const BN_LABELS = {
  personalInfo: 'ব্যক্তিগত তথ্য',
  physicalAttributes: 'শারীরিক বৈশিষ্ট্য',
  religiousInfo: 'ধর্মীয় তথ্য',
  education: 'শিক্ষাগত যোগ্যতা',
  professional: 'পেশাদার তথ্য',
  familyInfo: 'পারিবারিক তথ্য',
  siblingDetails: 'ভাই-বোনের বিবরণ',
  contactInfo: 'যোগাযোগের তথ্য',
  partnerPreferences: 'পাত্র/পাত্রীর পছন্দ',
  fullName: 'পূর্ণ নাম',
  dateOfBirth: 'জন্ম তারিখ',
  placeOfBirth: 'জন্মস্থান',
  nationality: 'জাতীয়তা',
  religion: 'ধর্ম',
  maritalStatus: 'বৈবাহিক অবস্থা',
  height: 'উচ্চতা',
  complexion: 'গায়ের রং',
  bloodGroup: 'রক্তের গ্রুপ',
  weight: 'ওজন',
  sect: 'মাজহাব',
  prayerHabit: 'নামাজের অভ্যাস',
  degree: 'ডিগ্রি',
  institution: 'প্রতিষ্ঠান',
  passingYear: 'পাসের বছর',
  result: 'ফলাফল',
  jobTitle: 'পদবি',
  organization: 'প্রতিষ্ঠান',
  duration: 'মেয়াদ',
  income: 'মাসিক আয়',
  fatherName: 'পিতার নাম',
  fatherOccupation: 'পিতার পেশা',
  motherName: 'মাতার নাম',
  motherOccupation: 'মাতার পেশা',
  brothers: 'ভাইয়ের সংখ্যা',
  sisters: 'বোনের সংখ্যা',
  familyType: 'পরিবারের ধরন',
  familyStatus: 'পারিবারিক অবস্থা',
  nativeDistrict: 'স্থায়ী জেলা',
  name: 'নাম',
  gender: 'লিঙ্গ',
  phone: 'ফোন',
  email: 'ইমেইল',
  presentAddress: 'বর্তমান ঠিকানা',
  permanentAddress: 'স্থায়ী ঠিকানা',
  ageRange: 'বয়সের পরিসীমা',
  educationPref: 'শিক্ষাগত যোগ্যতা',
  profession: 'পেশা',
  district: 'জেলা',
  otherRequirements: 'অন্যান্য প্রয়োজনীয়তা',
  male: 'পুরুষ',
  female: 'মহিলা',
  neverMarried: 'অবিবাহিত',
  divorced: 'তালাকপ্রাপ্ত',
  widowed: 'বিধবা/বিপত্নীক',
  nuclear: 'একক',
  joint: 'যৌথ',
};

export type BioLabels = typeof EN_LABELS;
